name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Build & Publish
      - name: Build
        run: |
          cd Backend/StudentsApi
          dotnet restore
          dotnet publish -c Release -o publish

      # Create production config
      - name: Create appsettings
        run: |
          echo '{
            "ConnectionStrings": {
              "DefaultConnection": "${{ secrets.RDS_CONNECTION }}"
            }
          }' > Backend/StudentsApi/publish/appsettings.Production.json

      # Copy files to EC2
      - name: Copy to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "Backend/StudentsApi/publish/*"
          target: "/home/ubuntu/studentapi"

      # Restart API
      - name: Restart API
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            pkill -f "dotnet" || true
            cd /home/ubuntu/studentapi
            nohup dotnet StudentsApi.dll --urls "http://0.0.0.0:5000" > app.log 2>&1 &
